### ISSUE TITLE
Get receipt-data to be used to verify an iTunes receipt

### ISSUE THREAD

**Issue by stumpykilo** [PackagedCat/nativescript-iap#11]
What is the strategy when restoring purchases for iOS? I think the logic must accommodate hitting `https://buy.itunes.apple.com/verifyReceipt` and then `https://sandbox.itunes.apple.com/verifyReceipt` according to https://developer.apple.com/documentation/appstorereceipts/verifyreceipt

Does the `restorePurchases` already handle this? I am coming from the `nativescript-purchase` library and it had a `getStoreReceipt` (https://github.com/PeterStaev/nativescript-purchase/blob/master/purchase.ios.ts) method but I don't see the equivalent here.

**Comment by PackagedCat** [comment]
Hello @stumpykilo 
Currently "nativescript-iap" doesn't have functions to verify receipt, but I looking for a way to implement this. Does `getStoreReceipt` from "nativescript-purchase" helpfull? According to documentation, verification receipt is more complex than solution in "nativescript-purchase" package.

**Comment by stumpykilo** [comment]
I'm not sure if it is necessary anymore but I know at one time Apple required the handling of it. This is what my code looked like using the `nativescript-purchase` library:
```
                ns-purchase.restorePurchases()
                .then(() => {
                    if (platformModule.isIOS)
                    {
                        var receipt = purchase.getStoreReceipt();

                        axios.post('https://buy.itunes.apple.com/verifyReceipt', {
                            "receipt-data": receipt
                        })
                        .then(function (response) {
                            console.log(response);
                            
                            if (response.data.status == "21007")
                            {
                                axios.post('https://sandbox.itunes.apple.com/verifyReceipt', {
                                    "receipt-data": receipt
                                })
                                .then(function (response) {
                                    console.log(response);
                                })
                                .catch(function (error) {
                                    console.log(error);
                                    alert('There was an error restoring your purchases.');
                                });
                            }
                        })
                        .catch(function (error) {
                            console.log(error);
                            alert('There was an error restoring your purchases.');
                        });
                    }
                })
```
Might be nice to handle both the `getStoreReceipt` logic and posting to the `verifyReceipt` endpoint inside your library.

**Comment by ArthurMJ96** [comment]
You aren't allowed to verify receipts inside the App anyways.

From: https://developer.apple.com/documentation/storekit/original_api_for_in-app_purchase/validating_receipts_with_the_app_store
```
Warning

Do not call the App Store server verifyReceipt endpoint from your app. You can't build a trusted connection between a user’s device and the App Store directly, because you don’t control either end of that connection, which makes it susceptible to a machine-in-the-middle attack.
```

**Comment by PackagedCat** [comment]
@ArthurMJ96 For validating receipts on the device there is have another way:
https://developer.apple.com/documentation/appstorereceipts/validating_receipts_on_the_device

**Comment by stumpykilo** [comment]
I've been using this package for almost a year now and everything seems to be working great!
