### ISSUE TITLE
NativeClass is not defined

### ISSUE THREAD

**Issue by stumpykilo** [PackagedCat/nativescript-iap#12]
Getting the following error when trying to run app on an iPhone:

> NativeScript encountered a fatal error: Uncaught ReferenceError: NativeClass is not defined
> at
> ../node_modules/nativescript-iap/purchase/purchase.js(file: app/src/purchase/purchase.ios.ts:7:1)
> at __webpack_require__(file: app/webpack/bootstrap:816:0)
> at fn(file: app/webpack/bootstrap:120:0)
> at ../node_modules/nativescript-iap/index.js(file: app/src/index.ts:1:0)
> at __webpack_require__(file: app/webpack/bootstrap:816:0)
> at fn(file: app/webpack/bootstrap:120:0)
> at ../node_modules/babel-loader/lib/index.js!../node_modules/vue-loader/lib/index.js?!./components/Purchase.vue?vue&type=script&lang=js&(file:///app/bundle.js:975:74)
> at __webpack_require__(file: app/webpack/bootstrap:816:0)
> at fn(file: app/webpack/bootstrap:120:0)
> at ./components/Purchase.vue?vue&type=script&lang=js&(file: app/components/Purchase.vue?3a11:1:0)
> at __webpack_require__(file: app/webpack/bootstrap:816:0)
> at fn(file: app/webpack/bootstrap:120:0)
> at ./components/Purchase.vue(file: app/components/Purchase.vue:1:0)
> at __webpack_require__(file: app/webpack/bootstrap:816:0)
> at fn(fil<\M-b\M^@\M-&>
> *** Terminating app due to uncaught exception 'NativeScript encountered a fatal error: Uncaught ReferenceError: NativeClass is not defined
> at
> ../node_modules/nativescript-iap/purchase/purchase.js(file: app/src/purchase/purchase.ios.ts:7:1)
> at __webpack_require__(file: app/webpack/bootstrap:816:0)
> at fn(file: app/webpack/bootstrap:120:0)
> at ../node_modules/nativescript-iap/index.js(file: app/src/index.ts:1:0)
> at __webpack_require__(file: app/webpack/bootstrap:816:0)
> at fn(file: app/webpack/bootstrap:120:0)
> at ../node_modules/babel-loader/lib/index.js!../node_modules/vue-loader/lib/index.js?!./components/Purchase.vue?vue&type=script&lang=js&(file:///app/bundle.js:975:74)
> at __webpack_require__(file: app/webpack/bootstrap:816:0)
> at fn(file: app/webpack/bootstrap:120:0)
> at ./components/Purchase.vue?vue&type=script&lang=js&(file: app/components/Purchase.vue?3a11:1:0)
> at __webpack_require__(file: app/webpack/bootstrap:816:0)
> at fn(file: app/webpack/bootstrap:120:0)
> at ./components/Purchase.vue(file: app/components/Purchase.vue:1:0)
> at __webpack_requ<\M-b\M^@\M-&>

Here is what my package.json looks like:
```
  "dependencies": {
    "-": "0.0.1",
    "@nativescript/core": "8.0.8",
    "@nativescript/theme": "^3.0.0",
    "axios": "^0.19.2",
    "g": "^2.0.1",
    "nativescript": "^8.0.2",
    "nativescript-iap": "^7.1.0",
    "nativescript-purchase": "^2.0.13",
    "nativescript-ui-listview": "^9.0.2",
    "nativescript-vue": "^2.9.0",
    "vuex": "^3.5.1"
  },
  "devDependencies": {
    "@babel/core": "~7.1.0",
    "@babel/preset-env": "~7.1.0",
    "@nativescript/android": "8.0.0",
    "@nativescript/ios": "8.0.0",
    "@nativescript/webpack": "4.1.0",
    "babel-loader": "~8.0.0",
    "nativescript-vue-template-compiler": "^2.9.0",
    "node-sass": "^4.7.1",
    "vue-loader": "^15.9.7"
  }
```

**Comment by PackagedCat** [comment]
Hello @stumpykilo 
Fixed in 7.1.1 version
