### ISSUE TITLE
onPurchasesUpdated fails at notifying BillingResponseCode.USER_CANCELED

### ISSUE THREAD

**Issue by ArthurMJ96** [PackagedCat/nativescript-iap#9]
Your function `onPurchasesUpdated` in purchase.android.js (line:19) fails at `const nativeTransactions = purchases.toArray();` (line:22)  when the user cancels the dialog.

Some testing revealed that in a "Cancel" or "Fail" scenario the `purchases`-param is NULL.
Which makes the code fail when calling `.toArray()` on it.

This is problematic when trying to follow the Metadata guideline 
https://developer.android.com/google/play/billing/developer-payload#associate

**Comment by PackagedCat** [comment]
Hello @ArthurMJ96 
Thanks for pull request. I have updated pacakge to 7.1.0 version with this fix.

**Comment by ArthurMJ96** [comment]
No problem
Thank **you** for the great work on this plugin!
